os: linux
dist: focal
language: shell
services:
  - docker

script:
  - make test

before_deploy:
  - echo "${TRAVIS_TAG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_COMMIT}"
  - make build

deploy:
  provider: releases
  token: $GITHUB_DEPLOY_TOKEN
  file: ./build/distribution/BoxBilling.zip
  draft: true
  overwrite: true
  name: ${TRAVIS_TAG}
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

notifications:
  email: false
  slack: boxbilling:$SLACK_NOTIFICATIONS

branches:
  only:
    - master
    - /^\d+.\d+.\d+$/
